/**
 * This file was automatically generated by joi-to-typescript
 * Do not modify this file manually
 */

export interface broadcast {
  body: {
    message?: string;
  };
}

export interface connect {
  query?: object;
  websocket?: any;
}
